#!/usr/bin/perl

# File generated by menutray v0.52

# DO NOT edit this file!
# Any change in this file will be lost!
# Edit ~/.dotfiles/menutray/.config/menutray/schema.pl instead!

use utf8;
use strict;
use Gtk2 ('-init');

my $menu = 'Gtk2::Menu'->new;
my $icon = 'Gtk2::StatusIcon'->new;

my $menutray_title   = "menutray";
my $menutray_tooltip = "Applications";

if (defined($menutray_title) and 1) {
    $icon->set_title($menutray_title);
    $icon->set_name('');
}

if (defined($menutray_tooltip) and 1) {
    $icon->set_tooltip($menutray_tooltip);
}

$icon->set_from_icon_name('draw-cuboid');
$icon->set_visible(1);
$icon->signal_connect('button-release-event', \&show_icon_menu);

local $SIG{USR1} = \&show_icon_menu;

load_menu();

sub show_icon_menu {
    my (undef, $event) = @_;

    if (ref($event) and $event->button == 3) {

        my $right_click = 'Gtk2::Menu'->new;
        {
            my $regenerate = 'Gtk2::ImageMenuItem'->new("_Regenerate");
            $regenerate->set_property('tooltip_text', "Regenerate\ this\ menu\.");
            $regenerate->set_image('Gtk2::Image'->new_from_icon_name("gtk\-refresh",q{menu}));
            $regenerate->signal_connect('activate', sub {system "\/usr\/bin\/perl\ \\\/usr\\\/bin\\\/menutray\ \-i\ \-C\ \\\/home\\\/cory\\\/\\\.dotfiles\\\/menutray\\\/\\\.config\\\/menutray\\\/config\\\.pl\ \-S\ \\\/home\\\/cory\\\/\\\.dotfiles\\\/menutray\\\/\\\.config\\\/menutray\\\/schema\\\.pl\ \-o\ \\\/home\\\/cory\\\/\\\.dotfiles\\\/menutray\\\/\\\.config\\\/menutray\\\/menu\\\.pl &"; 'Gtk2'->main_quit});
            \$right_click->append($regenerate);
        }

        {
            my $quit = 'Gtk2::ImageMenuItem'->new("_Quit");
            $quit->set_property('tooltip_text', "Close\ this\ application\.");
            $quit->set_image('Gtk2::Image'->new_from_icon_name("application\-exit",q{menu}));
            $quit->signal_connect('activate', sub { 'Gtk2'->main_quit });
            \$right_click->append($quit);
        }

        $right_click->show_all;
        $right_click->popup(undef, undef, sub {
            my ($x, $y, @list) = Gtk2::StatusIcon::position_menu($right_click, 0, 0, $icon);
            ($x, $y) = @_[1,2] if 0;
            ($x, $y, @list);
        }, [1, 1], 0, 0);

        return 1;
    }
    $menu->popup(undef, undef, sub {
            my ($x, $y, @list) = Gtk2::StatusIcon::position_menu($menu, 0, 0, $icon);
            ($x, $y) = @_[1,2] if 0;
            ($x, $y, @list);
        }, [1, 1], 0, 0);

    return 1;
}

sub load_menu {
{
    my $item = 'Gtk2::ImageMenuItem'->new("_File\ Manager");
    $item->set_image('Gtk2::Image'->new_from_icon_name("system\-file\-manager",q{menu}));
    $item->signal_connect('activate', sub {system "xdg\-open\ \. &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("_Terminal");
    $item->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $item->signal_connect('activate', sub {system "urxvt &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("_Web\ Browser");
    $item->set_image('Gtk2::Image'->new_from_icon_name("web\-browser",q{menu}));
    $item->signal_connect('activate', sub {system "xdg\-open\ http\:\/\/ &"});
    $menu->append($item);
}

{
    my $item = 'Gtk2::ImageMenuItem'->new("_Run\ command");
    $item->set_image('Gtk2::Image'->new_from_icon_name("system\-run",q{menu}));
    $item->signal_connect('activate', sub {system "gmrun &"});
    $menu->append($item);
}


    $menu->append('Gtk2::SeparatorMenuItem'->new);

    # # # # # # # # # # # # # # # # # # # # ACCESSORIES # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("_Accessories");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-utilities",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("_About\ Xfce");
    $app->signal_connect('activate', sub {system "xfce4\-about &"});
    $app->set_property('tooltip_text', "Information\ about\ the\ Xfce\ Desktop\ Environment");
    $app->set_image('Gtk2::Image'->new_from_icon_name("help\-about",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Android\ File\ Transfer\ \(MTP\)");
    $app->signal_connect('activate', sub {system "android\-file\-transfer &"});
    $app->set_property('tooltip_text', "Transfer\ files\ from\/to\ MTP\ devices");
    $app->set_image('Gtk2::Image'->new_from_icon_name("android\-file\-transfer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Archive\ Manager");
    $app->signal_connect('activate', sub {system "file\-roller &"});
    $app->set_property('tooltip_text', "Create\ and\ modify\ an\ archive");
    $app->set_image('Gtk2::Image'->new_from_icon_name("org\.gnome\.ArchiveManager",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Bulk\ Rename");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/Thunar\/ThunarBulkRename &"});
    $app->set_property('tooltip_text', "Rename\ Multiple\ Files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("Thunar",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Calculator");
    $app->signal_connect('activate', sub {system "gnome\-calculator &"});
    $app->set_property('tooltip_text', "Perform\ arithmetic\,\ scientific\ or\ financial\ calculations");
    $app->set_image('Gtk2::Image'->new_from_icon_name("org\.gnome\.Calculator",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Character\ Map");
    $app->signal_connect('activate', sub {system "gucharmap &"});
    $app->set_property('tooltip_text', "Insert\ special\ characters\ into\ documents");
    $app->set_image('Gtk2::Image'->new_from_icon_name("accessories\-character\-map",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_compton");
    $app->signal_connect('activate', sub {system "compton &"});
    $app->set_property('tooltip_text', "Compositor\ for\ X11");
    $app->set_image('Gtk2::Image'->new_from_icon_name("compton",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_File\ Manager");
    $app->signal_connect('activate', sub {system "exo\-open\ \-\-launch\ FileManager &"});
    $app->set_property('tooltip_text', "Browse\ the\ file\ system");
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-file\-manager",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Fonts");
    $app->signal_connect('activate', sub {system "gnome\-font\-viewer &"});
    $app->set_property('tooltip_text', "View\ fonts\ on\ your\ system");
    $app->set_image('Gtk2::Image'->new_from_icon_name("org\.gnome\.font\-viewer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_KCharSelect");
    $app->signal_connect('activate', sub {system "kcharselect\ \-\-qwindowtitle &"});
    $app->set_property('tooltip_text', "Browse\ all\ unicode\ characters");
    $app->set_image('Gtk2::Image'->new_from_icon_name("accessories\-character\-map",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Terminal\ Emulator");
    $app->signal_connect('activate', sub {system "exo\-open\ \-\-launch\ TerminalEmulator &"});
    $app->set_property('tooltip_text', "Use\ the\ command\ line");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Thunar\ File\ Manager");
    $app->signal_connect('activate', sub {system "thunar &"});
    $app->set_property('tooltip_text', "Browse\ the\ filesystem\ with\ the\ file\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("Thunar",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Vim");
    $app->signal_connect('activate', sub {system "urxvt\ \-e\ \'vim\' &"});
    $app->set_property('tooltip_text', "Edit\ text\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gvim",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # DEVELOPMENT # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("_Development");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-development",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("_CMake");
    $app->signal_connect('activate', sub {system "cmake\-gui &"});
    $app->set_property('tooltip_text', "Cross\-platform\ buildsystem");
    $app->set_image('Gtk2::Image'->new_from_icon_name("CMakeSetup",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Electron");
    $app->signal_connect('activate', sub {system "electron &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("electron",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Qt\ Assistant");
    $app->signal_connect('activate', sub {system "assistant &"});
    $app->set_property('tooltip_text', "Shows\ Qt\ documentation\ and\ examples");
    $app->set_image('Gtk2::Image'->new_from_icon_name("assistant",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Qt\ Designer");
    $app->signal_connect('activate', sub {system "designer &"});
    $app->set_property('tooltip_text', "Design\ GUIs\ for\ Qt\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("QtProject\-designer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Qt\ Linguist");
    $app->signal_connect('activate', sub {system "linguist &"});
    $app->set_property('tooltip_text', "Add\ translations\ to\ Qt\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("linguist",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Qt\ QDbusViewer");
    $app->signal_connect('activate', sub {system "qdbusviewer &"});
    $app->set_property('tooltip_text', "Debug\ D\-Bus\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("qdbusviewer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Sublime\ Text");
    $app->signal_connect('activate', sub {system "\/opt\/sublime_text\/sublime_text &"});
    $app->set_property('tooltip_text', "Sophisticated\ text\ editor\ for\ code\,\ markup\ and\ prose");
    $app->set_image('Gtk2::Image'->new_from_icon_name("sublime\-text",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # EDUCATION # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("_Education");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-science",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Klavaro");
    $app->signal_connect('activate', sub {system "klavaro &"});
    $app->set_property('tooltip_text', "A\ very\ flexible\ and\ efficient\ touch\ typing\ tutor\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("klavaro",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # GRAPHICS # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("_Graphics");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-graphics",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Blender");
    $app->signal_connect('activate', sub {system "blender &"});
    $app->set_property('tooltip_text', "3D\ modeling\,\ animation\,\ rendering\ and\ post\-production");
    $app->set_image('Gtk2::Image'->new_from_icon_name("blender",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Blender\-2\.8");
    $app->signal_connect('activate', sub {system "blender\-2\.8 &"});
    $app->set_property('tooltip_text', "3D\ modeling\,\ animation\,\ rendering\ and\ post\-production");
    $app->set_image('Gtk2::Image'->new_from_icon_name("blender\-2\.8",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_GNU\ Image\ Manipulation\ Program");
    $app->signal_connect('activate', sub {system "gimp\-2\.10 &"});
    $app->set_property('tooltip_text', "Create\ images\ and\ edit\ photographs");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gimp",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Gravit\ Designer");
    $app->signal_connect('activate', sub {system "gravit\-designer &"});
    $app->set_property('tooltip_text', "gravit\-designer");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gravit\-designer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Inkscape");
    $app->signal_connect('activate', sub {system "inkscape &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ Scalable\ Vector\ Graphics\ images");
    $app->set_image('Gtk2::Image'->new_from_icon_name("inkscape",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Mirage");
    $app->signal_connect('activate', sub {system "mirage &"});
    $app->set_property('tooltip_text', "A\ fast\ GTK\+\ Image\ Viewer");
    $app->set_image('Gtk2::Image'->new_from_icon_name("mirage",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # MULTIMEDIA # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("_Multimedia");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-multimedia",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("_mpv\ Media\ Player");
    $app->signal_connect('activate', sub {system "mpv\ \-\-player\-operation\-mode\=pseudo\-gui\ \-\- &"});
    $app->set_property('tooltip_text', "Play\ movies\ and\ songs");
    $app->set_image('Gtk2::Image'->new_from_icon_name("mpv",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Qt\ V4L2\ test\ Utility");
    $app->signal_connect('activate', sub {system "qv4l2 &"});
    $app->set_property('tooltip_text', "Allow\ testing\ Video4Linux\ devices");
    $app->set_image('Gtk2::Image'->new_from_icon_name("qv4l2",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Qt\ V4L2\ video\ capture\ utility");
    $app->signal_connect('activate', sub {system "qvidcap &"});
    $app->set_property('tooltip_text', "Viewer\ for\ video\ capture");
    $app->set_image('Gtk2::Image'->new_from_icon_name("qvidcap",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_REAPER");
    $app->signal_connect('activate', sub {system "\"\/opt\/REAPER\/reaper\" &"});
    $app->set_property('tooltip_text', "REAPER");
    $app->set_image('Gtk2::Image'->new_from_icon_name("cockos\-reaper",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_VLC\ media\ player");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/vlc\ \-\-started\-from\-file &"});
    $app->set_property('tooltip_text', "Read\,\ capture\,\ broadcast\ your\ multimedia\ streams");
    $app->set_image('Gtk2::Image'->new_from_icon_name("vlc",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Volume\ Icon");
    $app->signal_connect('activate', sub {system "volumeicon &"});
    $app->set_property('tooltip_text', "Lightweight\ volume\ control\ for\ the\ systray");
    $app->set_image('Gtk2::Image'->new_from_icon_name("multimedia\-volume\-control",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # NETWORK # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("_Network");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-internet",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Avahi\ SSH\ Server\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/bssh &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\-enabled\ SSH\ Servers");
    $app->set_image('Gtk2::Image'->new_from_icon_name("network\-wired",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Avahi\ VNC\ Server\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/bvnc &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\-enabled\ VNC\ Servers");
    $app->set_image('Gtk2::Image'->new_from_icon_name("network\-wired",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Google\ Chrome");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/google\-chrome\-stable &"});
    $app->set_property('tooltip_text', "Access\ the\ Internet");
    $app->set_image('Gtk2::Image'->new_from_icon_name("google\-chrome",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Insync");
    $app->signal_connect('activate', sub {system "insync\ start &"});
    $app->set_property('tooltip_text', "Launch\ Insync");
    $app->set_image('Gtk2::Image'->new_from_icon_name("insync",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Mail\ Reader");
    $app->signal_connect('activate', sub {system "exo\-open\ \-\-launch\ MailReader &"});
    $app->set_property('tooltip_text', "Read\ your\ email");
    $app->set_image('Gtk2::Image'->new_from_icon_name("emblem\-mail",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Web\ Browser");
    $app->signal_connect('activate', sub {system "exo\-open\ \-\-launch\ WebBrowser &"});
    $app->set_property('tooltip_text', "Browse\ the\ web");
    $app->set_image('Gtk2::Image'->new_from_icon_name("web\-browser",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # OTHER # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("_Other");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-other",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Open\ Drive");
    $app->signal_connect('activate', sub {system "\"\/opt\/OpenDrive\/odrive\" &"});
    $app->set_property('tooltip_text', "Simple\ google\ drive\ client");
    $app->set_image('Gtk2::Image'->new_from_icon_name("odrive\-bin",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_OpenDrive");
    $app->signal_connect('activate', sub {system "\"\/home\/cory\/dwn\/OpenDrive\.0\.2\.2\.AppImage\" &"});
    $app->set_property('tooltip_text', "Simple\ google\ drive\ client");
    $app->set_image('Gtk2::Image'->new_from_icon_name("appimagekit\-odrive",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # SETTINGS # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("_Settings");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-accessories",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Add\/Remove\ Software");
    $app->signal_connect('activate', sub {system "pamac\-manager &"});
    $app->set_property('tooltip_text', "Add\ or\ remove\ software\ installed\ on\ the\ system");
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-software\-install",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Advanced\ Network\ Configuration");
    $app->signal_connect('activate', sub {system "nm\-connection\-editor &"});
    $app->set_property('tooltip_text', "Manage\ and\ change\ your\ network\ connection\ settings");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-system\-network",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_ARandR");
    $app->signal_connect('activate', sub {system "arandr &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("display",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Customize\ Look\ and\ Feel");
    $app->signal_connect('activate', sub {system "lxappearance &"});
    $app->set_property('tooltip_text', "Customizes\ look\ and\ feel\ of\ your\ desktop\ and\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-theme",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_File\ Manager");
    $app->signal_connect('activate', sub {system "thunar\-settings &"});
    $app->set_property('tooltip_text', "Configure\ the\ Thunar\ file\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-file\-manager",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Preferred\ Applications");
    $app->signal_connect('activate', sub {system "exo\-preferred\-applications &"});
    $app->set_property('tooltip_text', "Preferred\ Applications\ \(Web\ Browser\,\ Mail\ Reader\ and\ Terminal\ Emulator\)");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-default\-applications",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Removable\ Drives\ and\ Media");
    $app->signal_connect('activate', sub {system "thunar\-volman\-settings &"});
    $app->set_property('tooltip_text', "Configure\ management\ of\ removable\ drives\ and\ media");
    $app->set_image('Gtk2::Image'->new_from_icon_name("drive\-removable\-media",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Screensaver");
    $app->signal_connect('activate', sub {system "xscreensaver\-demo &"});
    $app->set_property('tooltip_text', "Change\ screensaver\ properties");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xscreensaver",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Software\ Update");
    $app->signal_connect('activate', sub {system "pamac\-manager\ \-\-updates &"});
    $app->set_property('tooltip_text', "Update\ software\ installed\ on\ the\ system");
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-software\-update",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_TLPUI");
    $app->signal_connect('activate', sub {system "tlpui &"});
    $app->set_property('tooltip_text', "A\ GTK\ user\ interface\ for\ TLP");
    $app->set_image('Gtk2::Image'->new_from_icon_name("tlpui",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # SYSTEM # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("_System");
    $app->set_image('Gtk2::Image'->new_from_icon_name("applications\-system",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Add\/Remove\ Software");
    $app->signal_connect('activate', sub {system "pamac\-manager &"});
    $app->set_property('tooltip_text', "Add\ or\ remove\ software\ installed\ on\ the\ system");
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-software\-install",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Android\ File\ Transfer\ \(MTP\)");
    $app->signal_connect('activate', sub {system "android\-file\-transfer &"});
    $app->set_property('tooltip_text', "Transfer\ files\ from\/to\ MTP\ devices");
    $app->set_image('Gtk2::Image'->new_from_icon_name("android\-file\-transfer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Avahi\ Zeroconf\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/avahi\-discover &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\ services\ available\ on\ your\ network");
    $app->set_image('Gtk2::Image'->new_from_icon_name("network\-wired",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Bulk\ Rename");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/Thunar\/ThunarBulkRename &"});
    $app->set_property('tooltip_text', "Rename\ Multiple\ Files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("Thunar",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Htop");
    $app->signal_connect('activate', sub {system "urxvt\ \-e\ \'htop\' &"});
    $app->set_property('tooltip_text', "Show\ System\ Processes");
    $app->set_image('Gtk2::Image'->new_from_icon_name("htop",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_ranger");
    $app->signal_connect('activate', sub {system "urxvt\ \-e\ \'ranger\' &"});
    $app->set_property('tooltip_text', "Launches\ the\ ranger\ file\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Software\ Update");
    $app->signal_connect('activate', sub {system "pamac\-manager\ \-\-updates &"});
    $app->set_property('tooltip_text', "Update\ software\ installed\ on\ the\ system");
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-software\-update",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Thunar\ File\ Manager");
    $app->signal_connect('activate', sub {system "thunar &"});
    $app->set_property('tooltip_text', "Browse\ the\ filesystem\ with\ the\ file\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("Thunar",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_urxvt");
    $app->signal_connect('activate', sub {system "urxvt &"});
    $app->set_property('tooltip_text', "An\ unicode\ capable\ rxvt\ clone");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_urxvt\ \(client\)");
    $app->signal_connect('activate', sub {system "urxvtc &"});
    $app->set_property('tooltip_text', "An\ unicode\ capable\ rxvt\ clone\ client\ for\ urxvtd");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_urxvt\ \(tabbed\)");
    $app->signal_connect('activate', sub {system "urxvt\-tabbed &"});
    $app->set_property('tooltip_text', "An\ unicode\ capable\ and\ tabbed\ rxvt\ clone");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_UXTerm");
    $app->signal_connect('activate', sub {system "uxterm &"});
    $app->set_property('tooltip_text', "xterm\ wrapper\ for\ Unicode\ environments");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xterm\-color_48x48",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_XTerm");
    $app->signal_connect('activate', sub {system "xterm &"});
    $app->set_property('tooltip_text', "standard\ terminal\ emulator\ for\ the\ X\ window\ system");
    $app->set_image('Gtk2::Image'->new_from_icon_name("xterm\-color_48x48",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # MENUTRAY # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk2::Menu'->new;
    my $app = 'Gtk2::ImageMenuItem'->new("_Menutray");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Config");
    $app->signal_connect('activate', sub {system "subl\ \\\/home\\\/cory\\\/\\\.dotfiles\\\/menutray\\\/\\\.config\\\/menutray\\\/config\\\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ configuration\ file");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Menu");
    $app->signal_connect('activate', sub {system "subl\ \\\/home\\\/cory\\\/\\\.dotfiles\\\/menutray\\\/\\\.config\\\/menutray\\\/menu\\\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ menu\ file\ for\ inspection");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("_Schema");
    $app->signal_connect('activate', sub {system "subl\ \\\/home\\\/cory\\\/\\\.dotfiles\\\/menutray\\\/\\\.config\\\/menutray\\\/schema\\\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ schema\ file\ to\ customize\ the\ menu");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    $menu->append('Gtk2::SeparatorMenuItem'->new);
{
    my $regenerate = 'Gtk2::ImageMenuItem'->new("_Regenerate");
    $regenerate->set_property('tooltip_text', "Regenerate\ this\ menu\.");
    $regenerate->set_image('Gtk2::Image'->new_from_icon_name("gtk\-refresh",q{menu}));
    $regenerate->signal_connect('activate', sub {system "\/usr\/bin\/perl\ \\\/usr\\\/bin\\\/menutray\ \-i\ \-C\ \\\/home\\\/cory\\\/\\\.dotfiles\\\/menutray\\\/\\\.config\\\/menutray\\\/config\\\.pl\ \-S\ \\\/home\\\/cory\\\/\\\.dotfiles\\\/menutray\\\/\\\.config\\\/menutray\\\/schema\\\.pl\ \-o\ \\\/home\\\/cory\\\/\\\.dotfiles\\\/menutray\\\/\\\.config\\\/menutray\\\/menu\\\.pl &"; 'Gtk2'->main_quit});
    $menu->append($regenerate);
}
{
    my $quit = 'Gtk2::ImageMenuItem'->new("_Exit");
    $quit->set_property('tooltip_text', "Close\ this\ application\.");
    $quit->set_image('Gtk2::Image'->new_from_icon_name("application\-exit",q{menu}));
    $quit->signal_connect('activate', sub { 'Gtk2'->main_quit });
    $menu->append($quit);
}
    $menu->show_all;
    return 1;
}
'Gtk2'->main;
