#!/bin/bash

title="Update Conf"
widthpercent=20

UPDATE_CONF=$(which update-conf.py)
KITTY_CONF=$(which kittyconf)

typeset -A menu
menu=(
  ["i3"]="$UPDATE_CONF -n i3wm"
  ["ncmpcpp"]="$UPDATE_CONF -n ncmpcpp"
)
