#!/bin/bash

title="Power Menu"
widthpercent=20

typeset -A menu
menu=(
  ["1: Launch Terminal ($TERMINAL)"]="$TERMINAL"
  ["2: Exit i3"]="i3exit"
  ["3: Log Off"]="kill -9 -1"
  ["4: Reboot"]="sudo reboot"
  ["5: Power Off"]="sudo poweroff"
)
