#!/bin/bash

title="Update Conf"
widthpercent=20

UPDATE_CONF=$(which update-conf.py)
KITTY_CONF=$(which kittyconf)

typeset -A menu
menu=(
  ["Dunst"]="$UPDATE_CONF -n dunst"
  ["i3"]="$UPDATE_CONF -n i3wm"
  ["Polybar"]="$UPDATE_CONF -n polybar"
  ["Kitty"]="$KITTY_CONF"
  ["Neofetch"]="$UPDATE_CONF -n neofetch"
  ["ncmpcpp"]="$UPDATE_CONF -n ncmpcpp"
)
