#!/bin/bash

title="System Menu"
widthpercent=20

typeset -A menu
menu=(
    ["1: Launch Terminal"]="urxvt"
    ["  Monitor Configuration"]="rofigen ~/.config/rofi/scripts/rofi-mons"
    ["3: Log Off"]="kill -9 -1"
    ["4: Reboot"]="sudo reboot"
    ["5: Power Off"]="sudo poweroff"
)
