alias ls='ls --color=auto'
alias ll='ls -la'
alias l.='ls -d .* --color=auto'
alias c='clear'
alias pacman='sudo pacman'
alias mkdir='mkdir -pv'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ping='ping -c 5'
alias i3config='vim $HOME/.config/i3/config'
alias pbconfig='vim $HOME/.config/polybar/config'
alias vmrc='vim $HOME/.vimrc'
alias xfresh='xrdb $HOME/.Xresources'
alias jekk='bundle exec jekyll serve'
alias scrot="scrot -e 'mv $f ~/pix/scrot/'"
alias whattime='tty-clock -c -C 3 -t -D'
